"""Literature validation: Akerboom et al., ACS Photonics 2022 (Validation E).

End-to-end check of BOTH stages against one paper, using the committed S4 optics
spectra under ``validations/validation E/data/optics/``:

  * optics  - S4-computed normal-incidence band-averaged emissivity (7.5-16 um)
              of the flat and microcylinder module glass vs the paper's 84.3 %
              and 97.7 % (Fig. 5a);
  * thermal - cooling_curve equilibrium temperature of the idealized bounds
              (Fig. 2d) and the three real stacks (Fig. 5b) vs the paper.

The spectra are regenerated by ``build_optics_s4.py`` (a genuine RCWA sweep, not
a fit). They are committed so this test needs no S4 build; the cylinder tolerance
absorbs the RCWA mode-truncation scatter (~0.5 %) documented in the README.
"""
import os

import numpy as np
import pytest

from radcoolpv import config as cm
from radcoolpv import pipeline
from radcoolpv._compat import trapz

VE = os.path.join(os.path.dirname(__file__), "..", "validations", "validation E")
BAND = (7.5, 16.0)

pytestmark = pytest.mark.skipif(
    not os.path.isdir(os.path.join(VE, "data", "optics")),
    reason="Validation E optics not built")


def _run(yaml_name):
    cfg = cm.load(os.path.join(VE, yaml_name))
    cfg.run.plots = False
    cfg.run.outputs = []                      # don't litter results/ during tests
    return pipeline.run(cfg)


def _band_average(lam, emit):
    m = (lam >= BAND[0]) & (lam <= BAND[1])
    return float(trapz(emit[m], lam[m]) / (BAND[1] - BAND[0]))


# --- thermal engine: idealized bounds, Fig. 2d ----------------------------

@pytest.mark.parametrize("yaml_name,paper_t", [
    ("bounds_zero.yaml", 366.5),
    ("bounds_window.yaml", 341.5),
    ("bounds_ideal.yaml", 330.5),
])
def test_theoretical_bounds(yaml_name, paper_t):
    t = _run(yaml_name).thermal.equil_temp
    assert abs(t - paper_t) < 6.0, f"{yaml_name}: {t:.1f} K vs paper {paper_t} K"


# --- S4 optics: band-averaged emissivity, Fig. 5a -------------------------

@pytest.mark.parametrize("yaml_name,paper_e,tol", [
    ("stack_flat.yaml", 84.3, 1.0),          # flat: converged, tight
    ("stack_cylinders.yaml", 97.7, 1.5),     # cylinders: RCWA-vs-FDTD method gap
])
def test_s4_band_emissivity(yaml_name, paper_e, tol):
    ctx = _run(yaml_name)
    avg = _band_average(ctx.optics.lambda_um, ctx.optics.emit) * 100.0
    assert abs(avg - paper_e) < tol, f"{yaml_name}: {avg:.1f}% vs paper {paper_e}%"


def test_cylinders_beat_flat_emissivity():
    """The whole point of the microcylinders: broadband AR raises emissivity."""
    flat = _band_average(*(lambda c: (c.optics.lambda_um, c.optics.emit))(
        _run("stack_flat.yaml")))
    cyl = _band_average(*(lambda c: (c.optics.lambda_um, c.optics.emit))(
        _run("stack_cylinders.yaml")))
    assert cyl > flat + 0.10                  # paper: 0.843 -> 0.977


# --- end to end: real-stack equilibrium temperature, Fig. 5b --------------

@pytest.mark.parametrize("yaml_name,paper_t", [
    ("stack_bare.yaml", 360.0),
    ("stack_flat.yaml", 339.0),
    ("stack_cylinders.yaml", 336.0),
])
def test_module_equilibrium_temperature(yaml_name, paper_t):
    t = _run(yaml_name).thermal.equil_temp
    assert abs(t - paper_t) < 2.0, f"{yaml_name}: {t:.1f} K vs paper {paper_t} K"
